---
fixes:
  - |
    Fixes an issue with the agent where the presence of a configuration drive
    from a prior node deployment could prevent networking configuration from
    being determined and loaded in DHCP-less use cases.
    The agent now attempts to identify the appropriate configuration drive
    networking data source utilizing the existing device identification
    process, and then triggers glean configuration to be re-generated,
    after which networking is restarted. For more information, please
    view `bug 2032377 <https://bugs.launchpad.net/ironic/+bug/2032377>`_.
security:
  - |
    The ironic agent is now able to re-assert networking configuration
    in DHCP-less modes should a prior node's ``config drive`` be
    discovered as readable. Normally this issue is not a security
    issue as long as ``ironic-python-agent-builder`` is utilized.
    Ironic's agent automatically exlcudes possible configuration
    drive copies from previously deployed baremetal nodes.
